name: framework
channels:
  - defaults
dependencies:
  - pip=22.1.2
  - python=3.7.13
  - pip:
    - beautifulsoup4==4.8.0
    - imdbpy==6.8
    - matplotlib==3.3.0
    - neo4j-driver==4.4.5
    - networkx==2.4
    - numpy==1.21.6
    - owlready2==0.22
    - pandas==1.2.0
    - pillow==9.2.0
    - protobuf==3.20.0
    - py2neo==2020.0.0
    - rdflib==6.0.2
    - scikit-learn==0.21.3
    - tensorflow==1.14.0
    - urllib3==1.26.12
    